2019-10-16 20:17:27,279 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:44]
2019-10-21 20:33:13,655 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:44]
2019-10-21 20:33:26,513 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:44]
2019-10-21 20:48:04,890 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:44]
2019-10-23 20:35:43,537 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-10-23 21:10:06,043 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-10-23 21:10:51,512 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-10-23 21:11:33,893 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-11-13 20:42:33,902 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 18:54:31,540 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 19:15:57,224 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 19:27:22,838 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 19:27:50,758 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 19:32:19,191 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 19:32:26,704 ERROR: Exception on /user/vishal2 [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/visha/Desktop/webprog1/web_prog_1/microblog/app/routes.py", line 79, in user
    posts = Post.query.filter_by(user_id=self.id)
NameError: name 'self' is not defined
2019-12-02 19:33:06,891 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 19:49:21,120 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:47]
2019-12-02 19:59:40,488 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:49]
2019-12-02 20:07:00,516 INFO: Microblog startup [in /Users/visha/Desktop/webprog1/web_prog_1/microblog/app/__init__.py:49]
2019-12-02 20:07:08,612 ERROR: Exception on /login [GET] [in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/visha/Desktop/webprog1/web_prog_1/microblog/app/routes.py", line 61, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/visha/Desktop/webprog1/web_prog_1/microblog/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/visha/Desktop/webprog1/web_prog_1/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/visha/Desktop/webprog1/web_prog_1/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/visha/Desktop/webprog1/web_prog_1/microblog/app/templates/login.html", line 15, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
